### ISSUE TITLE
License violation of c-ares, libev, libuv

### ISSUE THREAD

**Issue by isuruf** [conda-forge/gevent-feedstock#24]
These packages are vendored in, but their copyright statements and license notifications are not redistributed.

cc @conda-forge/core

**Comment by CJ-Wright** [comment]
This issue should also ping the maintainers @conda-forge/gevent

**Comment by nehaljwani** [comment]
@isuruf / @CJ-Wright Please review https://github.com/conda-forge/gevent-feedstock/pull/25
